### ISSUE TITLE
Truck Trunk Doesn't Open

### ISSUE THREAD

**Issue by DanyCryEn** [RuisSoftware/FiveM-Resources-2024#282]
Hi,
When i try open Trunk of Truck or Commercial vehicle, the message appears that there is no vehicle nearby

but with all compacts and other car , all work fine

**Comment by Maxamax1** [comment]
same issue

**Comment by Maxamax1** [comment]
i know its not pretty but its a solution you have to add the truck names to the vehicleTable trunk.lua:15 as a Example: ['pounder']=3
https://github.com/Maxamax1/FiveM-Resources/commit/ec88a1dce90b4154ee67757593fb897fc87f1d00
