### ISSUE TITLE
already weapon

### ISSUE THREAD

**Issue by DanyCryEn** [RuisSoftware/FiveM-Resources-2024#285]
Already_weapon when people have already weapon in inventory, but i don't want this... I wish I could give him the gun even if he already has one

**Comment by htmhyn** [comment]
in server/weapons.lua line 17. just change to this 

if targedCount >= 0 then

**Comment by DanyCryEn** [comment]
This is already to 0

**Comment by htmhyn** [comment]
tryit, im using it, no problem. it means if the person have 0 or more of the same weapon, u can still give it to them

**Comment by DanyCryEn** [comment]
i can't give weapon to player if hia have already same weapon on his inventory
